# NOTE: This docker-compose.yml is meant to be just an example of how
# you could accomplish this on your own. It is not intended to work in
# all use-cases and must be adapted to fit your needs. This is merely
# a guideline.

# See docs.getsentry.com/on-premise/server/ for full
# instructions

version: '2'
services:
  base:
    hostname: base
    restart: unless-stopped
    build: .
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp
    volumes:
      - ./data/sentry:/var/lib/sentry/files

  smtp:
    hostname: smtp
    restart: unless-stopped
    image: tianon/exim4
    networks:
      - sentry_platform

  memcached:
    hostname: memcached
    restart: unless-stopped
    image: memcached:1.4
    networks:
      - sentry_platform    

  redis:
    hostname: redis
    restart: unless-stopped
    image: redis:3.2-alpine
    networks:
      - sentry_platform    

  postgres:
    hostname: postgres
    restart: unless-stopped
    image: postgres:9.5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - sentry_platform

  web:
    hostname: web
    restart: unless-stopped
    extends: base
    # links:
    #   - sentry-redis
    #   - sentry-postgres
    #   - sentry-memcached
    #   - sentry-smtp
    labels:
      - traefik.backend=web
      - traefik.docker.network=traefik_proxy
      - traefik.frontend.rule=Host:sentry.daton.it
      - "traefik.frontend.auth.basic=admin:$$apr1$$C8NRNJAO$$L.GDF3K7LfFut5CIa5bRM/"
      - traefik.port=9000
    networks:
      - traefik_proxy
      - sentry_platform
  
  cron:
    hostname: cron
    restart: unless-stopped
    extends: base
    command: run cron
    # links:
    #   - sentry-redis
    #   - sentry-postgres
    #   - sentry-memcached
    #   - sentry-smtp
    networks:
      - sentry_platform

  worker:
    hostname: worker
    restart: unless-stopped
    extends: base
    command: run worker
    # links:
    #   - sentry-redis
    #   - sentry-postgres
    #   - sentry-memcached
    #   - sentry-smtp
    networks:
      - sentry_platform

networks:
  traefik_proxy:
    external: true
  sentry_platform:
    external: false
    driver: bridge